services:
  database:
    image: postgres:16
    ports:
      - "54321:5432"
    volumes:
      - "database-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=P@ssw0rd"
      - "POSTGRES_DB=trainable"

volumes:
  database-data:

