"""Update model user_course

Revision ID: adefc7e06c06
Revises: 3c4a223bac47
Create Date: 2024-10-24 18:28:09.051817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adefc7e06c06'
down_revision = '3c4a223bac47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_courses', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('is_completed')

    # ### end Alembic commands ###
